### ISSUE TITLE
［要望］音量の指定方法を対数で出来るようにしたい

### ISSUE THREAD

**Issue by catcattoratora** [monoamp/Uniamp#1]
音量を調整の計算を対数で出来るようにしたいです。

**Comment by monoamp** [comment]
対応しました。

人が聴いて音量が直線的に変化するような指定方法は、スライダーの値（0〜1.0）の二乗の値を掛けるのが良さそうだったのでそれで実装しました。

**Comment by catcattoratora** [comment]
確認しました！
ありがとうございます！！
