### ISSUE TITLE
［要望］曲が終わった時に次の曲を再生したい

### ISSUE THREAD

**Issue by catcattoratora** [monoamp/Uniamp#2]
現在の仕様では曲が終わった時に同じ曲の最初に戻りますが、
次の曲に移行するようにしたいです。

**Comment by monoamp** [comment]
対応しました。実装した仕様は以下の通りです。

・ループ再生オンの場合
　ループ情報が埋め込まれている曲：ループ終了位置まで再生されたらループ開始位置へ移動
　ループ情報が埋め込まれていない曲：最後まで再生されたら同じ曲の先頭へ移動

・ループ再生オフの場合
　曲の最後まで再生されたら次の曲（最後の曲の場合は先頭の曲）を再生

**Comment by catcattoratora** [comment]
お疲れ様です。
下記の件、確認したところ別の不具合が出てきたので
別途チケットをあげます。

内容は、次の曲に進むときにノイズが入る場合があるというものです。
(いまの１から２に移るときは必ず起こります)

以上、よろしくお願いします。
