### ISSUE TITLE
[バグ]次の曲へ進むときにノイズが入る場合がある

### ISSUE THREAD

**Issue by catcattoratora** [monoamp/Uniamp#3]
タイトル通りの内容です。
ループポイントを使わずにループする場合も入るようです。
（プチというノイズです）

よろしくお願いします。

**Comment by monoamp** [comment]
対応しました。

ノイズの入る箇所は曲の最後のサンプルで、誤った場所から値を取得しているのが原因でした。

**Comment by catcattoratora** [comment]
確認しました！
対応ありがとうございます。
